- .github/workflows/apply.yml
- .github/workflows/check.yml
Also add in the missing state bucket and dynamo secrets
> ci: Use the main branch for the reusable workflow

- .github/workflows/apply.yml
- common.tf
- templates/s3/log_bucket_policy.json.tpl
- ci: Add needs to the apply job.
- fix: Add SSL policy to log bucket and environment to VPC
> DR2 1090 ci and vpc fixes

- README.md
- common.tf
I've removed the existing EIPs from the terraform state and changed this
to a data block.
This will ensure that the EIP is not reallocated so we can give
Preservica a list of static IPs.
> feat: Remove EIP from terraform.

- deploy_roles.tf
- templates/iam_policy/deploy_lambda_policy.json.tpl
I've also changed the policy to take an array so I don't have to update
the json template every time there is a new lambda.
> Add terraform lambda to deploy policy.

- common.tf
- ingest_asset_opex_creator.tf
- templates/iam_policy/ingest_asset_opex_creator_policy.json.tpl
* Add the lambda
* Add a policy which allows
* Read from raw bucket
* Write to staging bucket
* Cloudwatch permissions
* Batch get permissions on the dynamo table
* Query permissions on the GSI
* Add the lambda role arn to the KMS policy
> DR2-1165 Terraform for ingest-asset-opex-creator lambda

- common.tf
- deploy_roles.tf
- ingest_folder_opex_creator.tf
- templates/iam_policy/ingest_folder_opex_creator_policy.json.tpl
Add the terraform for the folder opex lambda
Encrypt the dynamo table. The existing lambdas should work.
> DR2-1166 Folder opex creator

- deploy_roles.tf
- ip_lock_checker_lambda.tf
- templates/iam_policy/ip_lock_checker_policy.json.tpl
Also, add a scheduled event to message once per day
> Add IP locker lambda.

- ip_lock_checker_lambda.tf
The IP locking is in place so this won't be so annoying now.
> Update the IP lock lambda to run once per hour.

- common.tf
The terraform role was hard coded for integration.
> Use environment specific terraform roles

- common.tf
- templates/eventbridge/step_function_failed_event_pattern.json.tpl
- templates/iam_policy/ingest_step_function_policy.json.tpl
This will send a slack alert if the step function status becomes FAILED,
TIMED_OUT or aborted and will send a message to the Slack destination.
> Eventbridge rule for step function failure.

- templates/iam_policy/ingest_step_function_policy.json.tpl
This doesn't work with the InvokeFunction permission.
> Remove the :* from the policy.

- common.tf
- Small fixes to allow testing on staging.
- Add sample files bucket
> DR2-1245 create sample files bucket

- common.tf
- deploy_roles.tf
- e2e_tests.tf
- templates/iam_policy/e2e_tests_execution_policy.json.tpl
- templates/iam_policy/e2e_tests_task_policy.json.tpl
- templates/iam_policy/run_e2e_tests_task.json.tpl
- templates/task_definitions/e2e_tests.json.tpl
* ECS task definition
* ECS task role
* ECS execution role
* Role to run the ECS task in GitHub
> DR2-1328 Resources for e2e tests

- .terraform.lock.hcl
- common.tf
- DR2-1375 Add eventbridge rule for general notifications
- Rename the new rule
> DR2 1375 add general notification eventbridge rule

- common.tf
Prod uses different channels, this will update them.
I've already changed this manually
> Update to use prod channel

- ingest_asset_reconciler.tf
This is talking to Preservica so needs to be in the VPC
> Add reconciler to VPC.

- deploy_roles.tf
- templates/iam_policy/deploy_lambda_policy.json.tpl
Also, addsome missing lambdas to the deploy policy temporarily and add
the ListBucket permission for the code deploy role.
> DR2-1549 Update to allow eventbridge publish

- .terraform.lock.hcl
- common.tf
- templates/iam_policy/ingest_step_function_policy.json.tpl
Also, correct typo on the step function policy.
> DR2-1520 Add lock table.

- disaster_recovery.tf
- templates/iam_policy/disaster_recovery_policy.json.tpl
This isn't related to any specific repository, it just allows them to
call get-authorization-token.
> Allow DR user to get a token.

- common.tf
- ingest_asset_opex_creator.tf
- ingest_asset_reconciler.tf
- ingest_folder_opex_creator.tf
Sadly we can't have a boolean index so this is a string and we'll need
to rely on the DynamoFormatters to make sure this doesn't get into a
mess.
The rest of the changes are renaming and reformatting as we've got more
than one index now.
> DR2-1563 Add new GSI on ingested_PS

- get_latest_preservica_version.tf
- templates/dynamo/dr2_preservica_version.json.tpl
We should be using the demo secret in both places. We're using our one
in the policy.
Also, the version should be a number to match what's in the case class.
> Use demo secret and change column type.

- deploy_preservica_config.tf
- entity_event_generator.tf
- get_latest_preservica_version.tf
- ingest_asset_opex_creator.tf
- ingest_asset_reconciler.tf
- ingest_check_preservica_for_existing_io.tf
- ingest_folder_opex_creator.tf
- ingest_mapper.tf
- ingest_parent_folder_opex_creator.tf
- ingest_parsed_court_document_event_handler.tf
- ingest_start_workflow.tf
- ingest_upsert_archive_folders.tf
- ingest_workflow_monitor.tf
This can be merged after
https://github.com/nationalarchives/dr2-ingest/pull/103 is deployed.
> DR2-1701 rename packages

- common.tf
- deploy_roles.tf
- ingest_check_preservica_for_existing_io.tf
In an attempt not to make breaking changes, I'm creating the lambda with
the new name first.
Then I'll change dr2-ingest to deploy to this new lambda.
Then I'll switch over the step functions to the new one and delete the
old one.
> DR2-1715 Create lambda with new name.

- common.tf
- templates/sfn/ingest_sfn_definition.json.tpl
None of these will work seperately so I'm lumping them into the same change
> DR2-1730 DR2-1750 Rename table, change primary key, update SFN

- README.md
- common.tf
- custodial_copy_notifications.tf
- disaster_recovery.tf
- templates/iam_policy/disaster_recovery_policy.json.tpl
* Add the DLQ to the alarm.
* Add the new repos to the DR user
* Subscribe the new queue to the DR notifications topic
> DR2-1769 Create SQS queue

- common.tf
Enabled stream for files table 
Depends on  https://github.com/nationalarchives/da-terraform-modules/pull/59
Do not merge before merging the above mentioned PR.
> DR2-1771-Use-the-new-dynamo-stream-in-dr2-terraform-environments

- rotate_preservation_system_password.tf
We won't need them. Will need to be deployed alongside
https://github.com/nationalarchives/dr2-ingest/pull/175
> Remove user and secret name env vars.

- custodial_copy_notifications.tf
- deploy_roles.tf
This adds it to the deploy policy and the role trust policy and sets up
the sqs queue mapping.
> Run cc-notifications

- templates/iam_policy/custodial_copy_policy.json.tpl
This will allow the CC user to pull the new reindexer docker image.
> DR2-1847 Add reindexer image to user policy.

- tdr_preingest.tf
- templates/iam_policy/preingest_tdr_aggregator_policy.json.tpl
This matches the lambda and repo directory names
Also, add missing PutItem permission to the aggregator lambda role.
> Rename preingest packages

- templates/iam_policy/ingest_step_function_policy.json.tpl
- templates/sfn/ingest_sfn_definition.json.tpl
Also, use assetId. It's the same as assetName in the input but this
makes more sense.
> DR2-1776 Use deleteItem to remove lock table row.

- common.tf
- deploy_roles.tf
- ingest_failed_notifications.tf
- templates/iam_policy/failure_notifications_policy.json.tpl
This needs
https://github.com/nationalarchives/da-terraform-modules/pull/71 before
the tests will pass but it's ready for review.
> DR2-1910 Add ingest failure notifications lambda.

- ingest_failed_notifications.tf
I thought I'd done this but I forgot
> Use the correct package name

- custodial_copy_queue_creator.tf
> Attach queue creator to input queue.

- templates/sfn/ingest_run_workflow_sfn_definition.json.tpl
- templates/sfn/ingest_sfn_definition.json.tpl
Tested manually and working on intg, with @MancunianSam (15/11/2024).
> NOJIRA Remove `StatePayload` object from state data

- anonymiser.tf
- common.tf
- copy_files_from_tdr.tf
- custodial_copy.tf
- custodial_copy_notifications.tf
- custodial_copy_queue_creator.tf
- e2e_tests.tf
- external_notifications_log.tf
- ingest_asset_opex_creator.tf
- ingest_asset_reconciler.tf
- ingest_find_existing_asset.tf
- ingest_folder_opex_creator.tf
- ingest_mapper.tf
- ingest_parent_folder_opex_creator.tf
- ingest_parsed_court_document_event_handler.tf
- ingest_start_workflow.tf
- ingest_upsert_archive_folders.tf
- ingest_validate_generic_ingest_inputs.tf
- ingest_workflow_monitor.tf
- ip_lock_checker_lambda.tf
- root_provider.tf
- root_variables.tf
- tdr_preingest.tf
I've removed the assume roles section as we'll be assuming the role in
the GitHub action.
I've also removed the account number variable as we don't need it and
replaced everything inside with the data.aws_caller_identity block.
> DR2-2008 Update provider

- tdr_preingest.tf
This will need https://github.com/nationalarchives/da-terraform-modules/pull/91
to be merged before the tests will pass but I've checked it on
integration.
> DR2-2114 Enable ReportBatchItemFailures

- common.tf
This adds it to the developer key for all environments and the main key
for intg and staging.
> DR2-2099 Add wiz role to keys

- common.tf
https://docs.aws.amazon.com/step-functions/latest/dg/concepts-error-handling.html#error-handling-retrying-after-an-error
> Add Jitter strategy

- common.tf
- templates/logs/logs_resource_policy.json.tpl
* Deleted the log group
* Removed datsync from the Cloudwatch resource policy.
> DR2-2116 Remove datasync resources.

- common.tf
- reporting_dashboard.tf
- templates/iam_policy/ingest_reporting_policy.json.tpl
- templates/iam_policy/reporting_helper_policy.json.tpl
- templates/s3/cloudfront_bucket_access_policy.json.tpl
Added the terraform infrastructure 
- S3 bucket, lambda, cloudwatch eventbridge, cloudfront
> Dr2 2205 reporting infrastructure terraform

- common.tf
- templates/sfn/ingest_run_workflow_sfn_definition.json.tpl
Requires nationalarchives/da-terraform-modules#115.
> DR2-2144 Add custom, linear retires for the Upsert Lambda

- postingest/postingest.tf
- postingest/templates/policies/message_resender_lambda_policy.json.tpl
* Add the environment variables to the lambda
* Add missing permissions to the lambda policy
> Fixes for resender

- preingest/templates/preingest_package_builder_policy.json.tpl
The package builder needs this. I'm not sure how I missed it.
> Add ListBucket permission.
