README.md
common.tf
deploy_preservica_config.tf
disaster_recovery.tf
download_metadata_and_files_lambda.tf
templates/iam_policy/preservica_config_policy.json.tpl
templates/s3/preservica_config_bucket_policy.json.tpl
templates/sns/s3_notifications_policy.json.tpl
templates/sqs/sns_send_message_policy.json.tpl

Add Preservica config lambda.
I've used this PR to update the existing S3 buckets and SQS queues to use KMS.
There are two keys. dr2_kms_key only has the download_metadata_files lambda role allowed to encrypt and decrypt.
dr2_developer allows the developer admin roles to encrypt and decrypt.
This will be used for config buckets and queues like preservica config and the deploy bucket.
The tests won't pass on this until https://github.com/nationalarchives/da-terraform-modules/pull/9 is merged but this is ready for review.

DR2-1093 Preservica Config Lambda

---

common.tf

As per https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/encrypt-log-data-kms.html
The region name is needed. You get an error creating encrypted log
groups if it's omitted.
Needs https://github.com/nationalarchives/da-terraform-modules/pull/14
before this can be deployed.

DR2-1092 Add region to logs service name.

---

.github/workflows/apply.yml
README.md
common.tf
deploy_preservica_config.tf
disaster_recovery.tf
download_metadata_and_files_lambda.tf
ingest_mapper.tf
ingest_parsed_court_document_event_handler.tf
root_provider.tf
root_variables.tf
slack_notifications_lambda.tf

I've updated the README and the GitHub workflow files with the new name.
I've also renamed dp_account_number to account_number. This then matches other non-dr2 terraform repos so we can use the same shared job.
I've not changed the state buckets because then we'd have to migrate the state and I don't think it's confusing anyone.

DR2-1168 feat: Replace DP with DR2

---

common.tf
disaster_recovery.tf
ingest_parsed_court_document_event_handler.tf
templates/s3/lambda_access_bucket_policy.json.tpl

This bucket will probably have more than one lambda accessing it so I've
changed the lambda bucket policy template to accept an array instead of
a single lambda. I've updated the other buckets that use this template.
This has no effect at the moment because the account has access to the
bucket by default but if we want to change the policy to a deny unless
style one later, this will help.
The raw cache bucket has already been created under another PR.

Add ingest raw staging bucket.

---

deploy_roles.tf

This allows GitHub actions to deploy the lambda. I missed it in the
original terraform PR.

Add asset_opex_creator to deploy role

---

templates/iam_policy/ingest_upsert_archives_folder_policy.json.tpl

Add put events to upsert lambda.
Also update the da-configurations hash. The changes are from other teams so don't affect us but it's nice to keep it up to date.

DR2 1217 add put events policy

---

templates/iam_policy/entity_event_lambda_policy.json.tpl

The AWS client is now using BatchGetItem instead of GetItem so the
policy needs changing.

Update entity event generator policy.

---

common.tf
ingest_parsed_court_document_event_handler.tf

The first is to allow the admin role to use the KMS key which lets us
put and get stuff from the test input bucket.
The second is to shorten the name of the bucket because
staging-ingest-parsed-court-document-event-handler-test-input-logs is
too long. We may not need individual log buckets in the future but for
now, this will do.

Small fixes to allow testing on staging.

---

templates/sfn/ingest_sfn_definition.json.tpl

Without the dollar sign it was showing {account_id} rather than the
account id. This should work now.

Add dollar sign

---

ingest_upsert_archive_folders.tf
templates/sfn/ingest_sfn_definition.json.tpl

If we send more than one judgment message through at once, there is a
race condition on the upsert lambda so multiple of the same folder are
being created.
To prevent this, this sets the reserved concurrency to 1 and ups the
retries in the step function.
This is a temporary fix as it won't work if we have to migrate thousands
but it'll work for our testing.

Add more retries and add reserved concurrency

---

e2e_tests.tf
templates/task_definitions/e2e_tests.json.tpl

There is a difference between the container definition in the json and
the task definition in the terraform resource.
This needs more attributes in the resource. I can't get 1024 cpu and
3072 memory to work so I've reduced it to 2048 which doesn't seem to
have affected anything.

Fix the task definition.

---

s3_copy.tf

Sometimes, the s3 copy lambda is running out of memory.
As this is hopefully a temporary lambda, I don’t want to
spend time working out why so we just need to increase it.
I’ve tried it at 1024Mb and that works.

DR2-1391 Increase S3 copy lambda memory

---

anonymiser.tf
common.tf
deploy_roles.tf
download_metadata_and_files_lambda.tf

The bucket name had to be changed because sadly, prod-disaster-recovery
is taken.
The dev kms key was still using the old service_names parameter which
didn't do anything. I've updated it to use the service_details variable
which does.
I've also added the cloudwatch logs service to the main key. We're not
currently using it but we probably will.
I've removed the anonymiser lambda and queue for environments that weren't integration. They weren't connected to anything but it's a bit pointless having them around doing nothing.

DR2-1225 Fix KMS policies and bucket name

---

templates/sfn/ingest_sfn_definition.json.tpl

The way it was set with a interval of 2 and a backoff rate of 4 meant
that we could be waiting around 9 days for an ingest to complete which
wouldn't work.
What we need is for it to try a lot of times in quick succession. Once
the initial 30s run from a cold lambda is done, the execution time of
the upsert lambda is ~1s.
These settings will try every 5 seconds up to 15 times so up to 75
seconds in total. This should give us plenty of time to process quite a
few concurrent step functions before we hit the max retries.
This could all be wrong though. All we can do is try it and see what
comes out of the testing later.

DR2-1419 Update upsert lambda retries.

---

anonymiser.tf
deploy_preservica_config.tf
download_metadata_and_files_lambda.tf
ingest_parsed_court_document_event_handler.tf

This change allows us to ignore any manual changes to the status of the
queue mappings.
This depends on https://github.com/nationalarchives/da-terraform-modules/pull/33 The tests won't pass until this is merged.

DR2-1420 use new SQS mappings variable.

---

anonymiser.tf
common.tf
deploy_roles.tf
download_metadata_and_files_lambda.tf
templates/logs/ingest_dashboard.json.tpl

Also, rename the disaster recovery bucket.
Also, remove the anonymiser queue and download files queue from the dashboard. The anonymiser queue isn't in staging or prod and the download files queue isn't even used so they don't need to be here.

Don't create the anonymiser lambda in staging and prod

---

templates/iam_policy/ingest_step_function_policy.json.tpl

These are needed to run the new redrive feature.
We need two arns because the first one is the distributed map which in
effect creates a new step function execution with the name
"Intg-ingest/StagingCacheS3ObjectKeys"
I've tested this on integration and it lets me re-run the step
functions.

Add RedriveExecution permissions.

---

ingest_mapper.tf
ingest_parsed_court_document_event_handler.tf

Increase timeouts

---

templates/sfn/ingest_sfn_definition.json.tpl

The States.ALL error needs to be in a retrier on its own.
Also, the success step wasn't called from anywhere so it can be deleted.

Refactor retries.

---

common.tf
templates/eventbridge/guard_duty_slack_message.json.tpl
templates/eventbridge/source_detail_type_event_pattern.json.tpl

Add Guard Duty finding alerts.
I can't seem to use the existing slack template as terraform gets very
upset when I try to use newlines inside a json template.
I've also hard coded the prod dev channel in the slack template so we
don't lose any findings in the other noise.

DR2-1484 Guard duty alerts

---

disaster_recovery.tf
entity_event_generator.tf
templates/iam_policy/disaster_recovery_policy.json.tpl

This is the user which will be used by the disaster recovery service.
We also didn't have a terraformed entity event queue listening to the
topic so I've added this in.

DR2-1584 Create entity queue and DR user

---

anonymiser.tf
common.tf
ingest_parsed_court_document_event_handler.tf

The new anonymiser lambda was writing to the wrong bucket and sending a
message with the old bucket.
The KMS key didn't have the new anonymiser lambda in it's list of
allowed decrypt roles.
The new parsed document handler was starting the old step function.

Fixes for things I missed the first time

---

anonymiser.tf
ingest_parsed_court_document_event_handler.tf

For the prod queue linked to the TRE topic, I've added a num
subscription to the new queue. Before I deploy this, I'll disable the
trigger for the court document lambda. Then if any messages come through
while this subscription is being added, we won't lose them.
If I just change the subscription, there'll be a tiny window where
there'll be no subscription and sod's law says we'll get a message then
so this is safer.
For the anonymiser queue, we don't care if we lose a message so this is
just being replaced.

DR2-1591 Add new queue to topic subscription.

---

deploy_roles.tf
e2e_tests.tf
templates/iam_role/github_assume_role.json.tpl

These should be limited only to the environments and repositories that
they need

DR2-1639 Update Github actions role trust policy.

---

common.tf
deploy_preservica_config.tf
templates/s3/lambda_access_bucket_policy.json.tpl
templates/s3/preservica_config_bucket_policy.json.tpl

* The dev kms key was using the old variable and so didn't have
permissions for s3/sns etc.
* The newest da-terraform-modules adds the SSL only block for buckets so
we don't need it here.
* The preservica config SNS topic had the wrong name and a mismatch
between the resource in its policy and its name.

Small terraform fixes

---

common.tf

This is a column for ttl so it's called ttl. There is no need to make
this any longer.
This will need deploying manually because the call needs KMS decrypt
permissions which terraform doesn't and shouldn't have.
The tests won't pass until https://github.com/nationalarchives/da-terraform-modules/pull/55 is merged but it's ready for review.

DR2-1728 Add ttl column to the files table.

---

templates/task_definitions/e2e_tests.json.tpl

It was complaining about this not being set.
I think it will still work because we have bind mounts into the
container with readonly false so we can write files in certain
directories (I think)
If it doesn't work, we're not using them at the moment anyyway.

Fix alert for e2e tests

---

common.tf
templates/eventbridge/secrets_manager_rotation.json.tpl

We get one for RotationFailed and RotationSucceeded.
Because of the way the transformers work I've not included the error
message as it makes the terraform messy. This is find because Slack is
not a debugging tool.

DR2-1772 Secrets rotation and notifications.

---

ingest_parsed_court_document_event_handler.tf

This also removes it from the dlq.

DR2-1718 Remove encryption from court document handler queue.

---

common.tf
external_notifications_log.tf
sns_notifications.tf
templates/iam_policy/external_notification_log_pipe_policy.json.tpl
templates/iam_role/service_source_account_only.json.tpl
templates/pipes/sqs_to_cloudwatch_target_transformer.json.tpl

Anything going to the notifications topic will go
SNS -> SQS -> Eventbridge pipe -> Cloudwatch.
There is an input transformer configured so we don't get all the output
from the SQS message.
Given an SNS message:
```json
{
"id": 1,
"message": "Another test message"
}
```
You will end up with this in Cloudwatch:
```json
{
"body": {
"id": 1,
"message": "Another test message"
},
"timestamp": "1720607411035"
}
```

DR2-1755 Log external notifications

---

common.tf

Simple one line change to enable delete protection

DR2-1768-Enable-deletion-protection-on-dr2-ingest-files

---

templates/sfn/ingest_sfn_definition.json.tpl

This step is now being done by the files change handler. Or it should
be, I'm not convinced it's working but it's harder to debug with this
sending as well and we won't need this if the files change handler
works properly so it can be removed.

Remove notifications publish.

---

common.tf

These are annoying and not necessary. The failed ones will still alert.

Remove secrets manager success notification.

---

copy_files_from_tdr.tf
templates/iam_policy/copy_files_from_tdr_policy.json.tpl

When you're doing cross account KMS, you need permissions on both ends.
I've updated TDR so it needs doing in the lambda policy

Add permissions for TDR KMS.

---

tdr_preingest.tf

The environment variables of the lambda should be linked to the batch
configuration so that the lambda code knows when to create a new batch.

Link batch variables to env vars.

---

common.tf

Setting this to false changes the encryption to AWS managed.

DR2-1859 Remove kms encryption from the lock table

---

tdr_preingest.tf
templates/iam_policy/preingest_tdr_package_builder_policy.json.tpl

The package builder needs to read the TDR metadata from S3 and write our
metadata out.
I've added the bucket as an environment variable rather than read it out
of one of the lock table messages.

Add S3 permissions and env vars

---

templates/sfn/preingest_tdr_sfn_definition.json.tpl

We shouldn't have an output path and the ingest step function is
expected metadataPackage, not packageMetadata.
I will change the package builder to match at some point.

Preingest sfn fixes

---

common.tf

We're not getting alerts when there are errors in the main custodial
copy queue. This should sort it.

Add the main cc queue.

---

copy_files_from_tdr.tf

This lets us stop TDR transfers coming in. The messages will just sit in
the queue.

Ignore the enabled status for the copy files queue.

---

common.tf
custodial_copy.tf
custodial_copy_queue_creator.tf
deploy_roles.tf
entity_event_generator.tf
templates/iam_policy/custodial_copy_queue_creator_policy.json.tpl

This creates the lambda which will add the IO id as the message group id
and creates the queue which triggers it.
I've updated the entity event topic to send to the new queue and updated
the existing custodial copy queue to be a fifo queue.
I've added the new sqs queue to the alarms and added the lambda to the
deploy policy.
This needs
https://github.com/nationalarchives/da-terraform-modules/pull/67 before
this will work.

DR2-1889 FIFO queue and creator lambda

---

common.tf

We're getting timeout errors on the ingest mapper for TDR transfers of
1000 files.
This will just increase all the lambda timeouts which I think is fine.
This is probably not the final value, we just need to do some testing to
see what the best values are.

Increase lambda timeout.

---

entity_event_generator.tf

Because the reserved concurrency wasn't set, we were sometimes getting
multiple lambdas reading Preservica at the same time and publishing the
messages more than once.
Also, we don't want this running over 60 seconds and having another
lambda read from Preservica before we've had a chance to update Dynamo

DR2-1896 Set reserved concurrency and timeout.

---

templates/sfn/ingest_sfn_definition.json.tpl

If the Preservica workflow fails, some assets may have been ingested and
we want these to progress and send their complete messages which they
won't if the step function fails.
The reconciler will return errors for the ones that haven't ingested.
I've reused the wait 5 minutes step just to tidy things up a bit. Most
ingests happen well before that and if not, another 5 minutes isn't
going to matter much.
I've also shortened the name of the state because the really wide boxes
make it difficult to see what's going on.

Reconcile on workflow failure.

---

ingest_parsed_court_document_event_handler.tf

We had a failed judgment on prod because the lambda ran out of memory.
I suspect it was because there was a 12Mb log file in there and we have
to parse everything in the tar.gz file.
We could look into why this happened and try to fix the code but I don't
want to dedicate time to dealing with tar.gz files so I'll apply 21st
century solutions and throw more memory at it.

Increase court document handler memory

---

common.tf
templates/iam_policy/ingest_step_function_policy.json.tpl
templates/sfn/ingest_sfn_definition.json.tpl

The distributed map which creates the asset opex needs to be batched otherwise we run out of lambda invocations.
The reconciler needs to stop outputing every failed child to Slack as this won’t work if there’s more than a few of them.
The reconciler also needs to send its output to S3 as it’s too large at the moment.
There are a few permissions updates needed and some of the SFN policy is out of date.

Step function updates

---

e2e_tests.tf

I suspect that the tests weren't taking over an hour, they were just
broken but they might if we start chucking bigger ingests through so I'm
going to add this in anyway.

Increase max session duration.

---

templates/sfn/preingest_tdr_sfn_definition.json.tpl

We changed the output to say metadataPackage but didn't update this.

Rename output variable.

---

common.tf
root_provider.tf

The changes to remove datasync are in prod so we don't need this any
more.
There'll be a manual step to empty the bucket before this can be
deployed.

DR2-1948 Delete staging cache bucket and provider.

---

custodial_copy.tf
custodial_copy_queue_creator.tf

The daily alarm is not that helpful so that's being deleted.
The other custodial copy ones have had their threshold raised to 50
because it's fairly common that we get more than that for a single
ingest.
This has already been deployed.

Remove daily alarm and increase thresholds.

---

common.tf
ingest_flow_control.tf
templates/iam_policy/ingest_flow_control_policy.json.tpl
templates/iam_policy/ingest_run_workflow_step_function_policy.json.tpl
templates/sfn/ingest_run_workflow_sfn_definition.json.tpl
templates/sfn/ingest_sfn_definition.json.tpl

* Make the run workflow step wait for a task token and pass the task token to the new step function
* Discard the output and return the input for that step
* Rename the run workflow step function invocation to ${ingest_sfn_name}-${random_uuid} This will let us redrive from the parent SFN
* Add a catch for Error States.ALL for both flow control lambdas and set the backoff rate to match the rest
* Update the permissions on the flow control lambda role as they were missing a couple
* Update the run workflow step function to send task success with the token passed as input.
* Update the policy to allow this.
* Send $.batchId instead of $$.Execution.Name to the start worfklow lambda.
* Add the ingest runner sub-workflow to the failed step function notifications.
* Use the arn in the message. …

DR2-2071 Use waitForTaskToken on ingest runner sub-workflow

---

tdr_preingest.tf

Configures the TDR Aggregation workflow to handle larger bursts of messages. It's unknown how many messages the Lambda can handle in a single invocation before timeout so I've reduced this for now - it's better to have multiple invocations build a group than an invocation timeout as the messages will keep looping in Lambda/SQS until the ingest for that asset is unlocked.

DR2-2086 Configure TDR Aggregator for larger message bursts

---

tdr_preingest.tf

Terraform was overwriting it if we had it disabled.

DR2-2105 Ignore changes to the TDR aggregator trigger.

---

common.tf
tdr_preingest.tf
templates/sfn/ingest_run_workflow_sfn_definition.json.tpl
templates/sfn/ingest_sfn_definition.json.tpl
templates/sfn/preingest_tdr_sfn_definition.json.tpl

The States.ALL error should catch any error that happens within the step
function, either from our code or from AWS.
We're fairly sure we don't need the specific Lambda exceptions.
The SDK calls to Dynamo, EventBridge and StepFunctions didn't have
retries either. So I've changed the template json files to take a
parameter and passed in the same retry block for all of them.
This should cover everything.

DR2-2089 Simplify and update retries

---

e2e_tests.tf
sns_notifications.tf
templates/iam_policy/e2e_tests_policy.json.tpl

The e2e tests have changed and need some new permissions and don't need
old ones. We also don't need the e2e-tests queue any more.

Update e2e-tests policy

---

common.tf

This was clashing with
`"${local.environment}-dr2-eventbridge-alarm-state-change-${lower(each.value)}"`
which comes out as the same thing when each.value is ALARM.

Name change to avoid clash.

---

.github/workflows/apply.yml
root_provider.tf

Dynamo locking has been deprecated. This will use s3 instead.
Needs https://github.com/nationalarchives/dr2-github-actions/pull/36 before this can merge

DR2-2215 Use S3 locking.

---

templates/ssm/ingest_flow_control_config.json.tpl

We have 2 environments and a single Job Queue server with 16 threads. We've been advised to use 10 threads in total for our activities, so limiting to 5 concurrent ingests per environment.

DR2-2139 Configure Ingest Flow Control

---

post_ingest/post_ingest.tf
templates/sfn/ingest_sfn_definition.json.tpl

We can't use ioRef for the PK because the output messages need to have
our reference, not Preservicas.
The confirmer job will need to contact Preservica to get their reference
from ours

Use assetId not ioRef

---

templates/sfn/ingest_sfn_definition.json.tpl

This way, the change handler can pass this to the CC confirmer which
will keep things much simpler.

Add ioRef as well.

---

postingest/outputs.tf

Minor change to output the lambda arn instead of the whole object.

Output the lambda arn

---

postingest/postingest.tf

What is happening is that the messages are being sent to CC confirmer 2
minutes before they actually make it into CC and we then have to wait an
hour for it to try again.
This will delay the sending of the message for 15 minutes.

Add delay of 15 minutes.
